export const WORKFLOW_STATUSES = [
  'DRAFT','ITF_CREATED','SENT_TO_ESTIMATION','UNDER_ESTIMATION_REVIEW','CLARIFICATION_REQUIRED',
  'CLARIFICATION_RECEIVED','JIF_IN_PROGRESS','JIF_COMPLETED','SENT_TO_DESIGN','UNDER_DESIGN_REVIEW',
  'DESIGN_QUERY_RAISED','WAITING_FOR_DESIGN_CLARIFICATION','DESIGN_IN_PROGRESS','DWS_COMPLETED',
  'RETURNED_TO_ESTIMATION','COSTING_IN_PROGRESS','COSTING_COMPLETED','COMMERCIAL_PROPOSAL_PREPARED',
  'TECHNICAL_PROPOSAL_PREPARED','PROPOSAL_PACKAGE_COMPLETED','SUBMITTED_TO_GM','UNDER_GM_REVIEW',
  'GM_REVISION_REQUIRED','GM_APPROVED','GM_REJECTED','FORWARDED_TO_SALES','READY_FOR_CLIENT_SUBMISSION',
  'SUBMITTED_TO_CLIENT','CLIENT_REVIEWING','FOLLOW_UP_REQUIRED','UNDER_NEGOTIATION',
  'REVISED_PROPOSAL_REQUIRED','WON','LOST','ON_HOLD','CANCELLED','ARCHIVED'
];

export const ROLE = { ADMIN:'ADMIN', SALES:'SALES', ESTIMATION:'ESTIMATION', DESIGN:'DESIGN', GM:'GM' };

export const DEPARTMENT_FOR_STATUS = {
  DRAFT:'Sales', ITF_CREATED:'Sales', SENT_TO_ESTIMATION:'Estimation', UNDER_ESTIMATION_REVIEW:'Estimation',
  CLARIFICATION_REQUIRED:'Sales', CLARIFICATION_RECEIVED:'Estimation', JIF_IN_PROGRESS:'Estimation',
  JIF_COMPLETED:'Estimation', SENT_TO_DESIGN:'Design', UNDER_DESIGN_REVIEW:'Design', DESIGN_QUERY_RAISED:'Estimation',
  WAITING_FOR_DESIGN_CLARIFICATION:'Estimation', DESIGN_IN_PROGRESS:'Design', DWS_COMPLETED:'Estimation',
  RETURNED_TO_ESTIMATION:'Estimation', COSTING_IN_PROGRESS:'Estimation', COSTING_COMPLETED:'Estimation',
  COMMERCIAL_PROPOSAL_PREPARED:'Estimation', TECHNICAL_PROPOSAL_PREPARED:'Estimation',
  PROPOSAL_PACKAGE_COMPLETED:'Estimation', SUBMITTED_TO_GM:'General Management', UNDER_GM_REVIEW:'General Management',
  GM_REVISION_REQUIRED:'Estimation', GM_APPROVED:'General Management', GM_REJECTED:'General Management',
  FORWARDED_TO_SALES:'Sales', READY_FOR_CLIENT_SUBMISSION:'Sales', SUBMITTED_TO_CLIENT:'Sales',
  CLIENT_REVIEWING:'Sales', FOLLOW_UP_REQUIRED:'Sales', UNDER_NEGOTIATION:'Sales', REVISED_PROPOSAL_REQUIRED:'Estimation',
  WON:'Sales', LOST:'Sales', ON_HOLD:'Sales', CANCELLED:'Sales', ARCHIVED:'Administration'
};
