import {useState} from 'react';
import {useParams,useNavigate} from 'react-router-dom';
import {useForm} from 'react-hook-form';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api,messageOf} from '../../api/client';
import {PageHeader,Spinner,Field,Confirm} from '../../components/common/UI';
import {ArrowLeft,CheckCircle2,RotateCcw,XCircle,Send,FileCheck2,Lock,FileText,FileSpreadsheet,Eye} from 'lucide-react';
import {useToast} from '../../context/ToastContext';
import StatusBadge from '../../components/common/StatusBadge';

const checklist=['ITF complete','JIF complete','DWS verified','Costing checked','Commercial terms reviewed','Technical scope reviewed','Drawings included','Taxes verified','Payment terms approved'];
const hidden=new Set(['_id','id','__v','save','createdAt','updatedAt','metadata','password','passwordHash','refreshTokens','passwordResetToken','passwordResetExpires','isDeleted','deletedAt']);
const primitive=value=>value===null||['string','number','boolean'].includes(typeof value);
const label=value=>String(value||'').replace(/[_-]+/g,' ').replace(/([a-z0-9])([A-Z])/g,'$1 $2').replace(/\b\w/g,x=>x.toUpperCase());
const display=value=>value===true?'Yes':value===false?'No':value===null||value===undefined||value===''?'—':/^\d{4}-\d{2}-\d{2}T/.test(String(value))?String(value).slice(0,10):String(value);
const entries=value=>Object.entries(value||{}).filter(([key,item])=>!hidden.has(key)&&item!==undefined&&item!==null&&item!=='');

export default function GMReviewPage(){
  const {id}=useParams(),navigate=useNavigate(),toast=useToast(),qc=useQueryClient(),[action,setAction]=useState(null),[downloading,setDownloading]=useState('');
  const {register,getValues}=useForm({defaultValues:{checklist:{},department:'Estimation'}});
  const {data,isLoading}=useQuery({queryKey:['gm-package',id],queryFn:()=>api.get(`/inquiries/${id}/package`).then(r=>r.data.data)});
  const ensureReview=async()=>{if(data.inquiry.currentStatus==='SUBMITTED_TO_GM')await api.post(`/inquiries/${id}/gm-review`,{checklist:getValues('checklist')})};
  const execute=async()=>{try{await ensureReview();if(action==='approve')await api.post(`/inquiries/${id}/gm-review/approve`,{comments:getValues('comments'),snapshot:{revision:data.inquiry.revisionNumber}});if(action==='revision')await api.post(`/inquiries/${id}/gm-review/request-revision`,{comments:getValues('comments'),department:getValues('department')});if(action==='reject')await api.post(`/inquiries/${id}/gm-review/reject`,{comments:getValues('comments')});if(action==='forward')await api.post(`/inquiries/${id}/gm-review/forward-to-sales`);toast(action==='approve'?'Package approved and locked':action==='forward'?'Approved package forwarded to Sales':'GM decision recorded');setAction(null);qc.invalidateQueries({queryKey:['gm-package',id]})}catch(e){toast(messageOf(e),'error')}};
  const download=async format=>{try{setDownloading(format);const response=await api.get(`/inquiries/${id}/package/${format}`,{responseType:'blob'}),url=URL.createObjectURL(response.data),anchor=document.createElement('a'),header=response.headers['content-disposition']||'',match=header.match(/filename="?([^";]+)"?/i);anchor.href=url;anchor.download=match?.[1]||`${data.inquiry.inquiryNumber}-GM-Package.${format==='word'?'docx':'xlsx'}`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);toast(`${format==='word'?'Word':'Excel'} package downloaded`)}catch(e){toast(messageOf(e),'error')}finally{setDownloading('')}};
  if(isLoading)return <Spinner/>;
  const i=data.inquiry,c=data.costing?.commercial||{},summary=[['Revision',`R${i.revisionNumber}`],['Building area',data.costing?.basics?.buildingArea],['Building weight',data.costing?.basics?.buildingWeight],['Final quotation',c.finalQuotationAmount?.toLocaleString()],['Profit margin',c.profitMarginPercentage!=null?`${c.profitMarginPercentage}%`:null],['Price / sq ft',c.pricePerSquareFoot?.toFixed(2)],['Price / kg',c.pricePerKilogram?.toFixed(2)],['Tax',c.taxAmount?.toLocaleString()]];
  const packageSections=[['Inquiry & Client',{...i,client:i.client}],['Inquiry Taking Form (ITF)',data.itf],['Job Inquiry Form (JIF)',data.jif],['Design Weight Summary (DWS)',data.dws],['Costing Sheet',data.costing],['Commercial Proposal',data.commercial],['Technical Proposal',data.technical],['Proposal Drawings',data.drawings]];
  return <>
    <PageHeader title="General Manager Review" description={`${i.inquiryNumber} • Complete proposal package`} actions={<div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>navigate(`/inquiries/${id}`)}><ArrowLeft size={17}/>Overview</button><button className="btn-secondary" disabled={Boolean(downloading)} onClick={()=>download('word')}><FileText size={17}/>{downloading==='word'?'Preparing…':'Download Word'}</button><button className="btn-secondary" disabled={Boolean(downloading)} onClick={()=>download('excel')}><FileSpreadsheet size={17}/>{downloading==='excel'?'Preparing…':'Download Excel'}</button></div>}/>
    {i.packageLocked&&<div className="mb-5 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800"><Lock/><div><b>Approved revision locked</b><p className="text-sm">Revision R{i.approvedRevision} is the official proposal package.</p></div></div>}
    <div className="grid gap-5 xl:grid-cols-3"><div className="space-y-5 xl:col-span-2">
      <section className="card p-5"><h2 className="font-bold text-navy-900">Executive summary</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{summary.map(([key,value])=><div key={key} className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{key}</p><p className="mt-1 font-bold text-navy-900">{value??'—'}</p></div>)}</div></section>
      <section className="card p-5"><h2 className="font-bold text-navy-900">Package documents</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[['ITF',data.itf],['JIF',data.jif],['DWS',data.dws],['Costing Sheet',data.costing],['Commercial Proposal',data.commercial],['Technical Proposal',data.technical],['Proposal Drawings',data.drawings?.length]].map(([key,value])=><div className="flex items-center justify-between rounded-lg border border-slate-200 p-3" key={key}><span className="text-sm font-medium">{key}</span>{value?<FileCheck2 className="text-emerald-600" size={19}/>:<StatusBadge status="MISSING"/>}</div>)}</div></section>
    </div><aside className="card h-fit p-5"><h2 className="font-bold text-navy-900">Decision</h2><Field label="Comments"><textarea className="field mt-4 min-h-28" {...register('comments')}/></Field><Field label="Return revision to"><select className="field" {...register('department')}><option>Estimation</option><option>Design</option></select></Field><div className="mt-4 space-y-2">{!i.packageLocked&&<><button className="btn-primary w-full bg-emerald-600 hover:bg-emerald-700" onClick={()=>setAction('approve')}><CheckCircle2 size={17}/>Approve & lock</button><button className="btn-secondary w-full" onClick={()=>setAction('revision')}><RotateCcw size={17}/>Request revision</button><button className="btn-danger w-full" onClick={()=>setAction('reject')}><XCircle size={17}/>Reject</button></>}{i.currentStatus==='GM_APPROVED'&&<button className="btn-primary w-full" onClick={()=>setAction('forward')}><Send size={17}/>Forward to Sales</button>}</div></aside></div>
    <section className="card mt-5 p-5"><div className="flex items-center gap-2"><Eye size={20} className="text-brand-700"/><div><h2 className="font-bold text-navy-900">Complete package details</h2><p className="text-sm text-slate-500">Open each section to review every saved field before making the GM decision.</p></div></div><div className="mt-4 space-y-3">{packageSections.map(([title,value])=><details key={title} className="overflow-hidden rounded-xl border border-slate-200 bg-white"><summary className="cursor-pointer select-none bg-slate-50 px-4 py-3 font-semibold text-navy-900">{title}</summary><div className="p-4">{value?<DataBlock value={value}/>:<p className="text-sm text-rose-600">No data available</p>}</div></details>)}</div></section>
    <Confirm open={Boolean(action)} title={action==='approve'?'Approve and lock revision?':action==='forward'?'Forward approved package to Sales?':'Record GM decision?'} message={action==='approve'?'The reviewed revision and all included documents will become immutable.':action==='revision'?'Comments are mandatory and the selected department stage will reopen.':'This action is recorded in the audit trail.'} onCancel={()=>setAction(null)} onConfirm={execute}/>
  </>;
}

function DataBlock({value}){
  if(Array.isArray(value))return <ArrayBlock value={value}/>;
  if(primitive(value))return <span>{display(value)}</span>;
  const scalarEntries=entries(value).filter(([,item])=>primitive(item)),nestedEntries=entries(value).filter(([,item])=>!primitive(item));
  return <div className="space-y-4">{scalarEntries.length>0&&<dl className="grid gap-3 sm:grid-cols-2">{scalarEntries.map(([key,item])=><div key={key} className="rounded-lg bg-slate-50 p-3"><dt className="text-xs font-medium text-slate-500">{label(key)}</dt><dd className="mt-1 break-words text-sm font-medium text-navy-900">{display(item)}</dd></div>)}</dl>}{nestedEntries.map(([key,item])=><div key={key}><h3 className="mb-2 text-sm font-bold text-brand-700">{label(key)}</h3><DataBlock value={item}/></div>)}</div>;
}

function ArrayBlock({value}){
  if(!value.length)return <p className="text-sm text-slate-500">No records</p>;
  if(value.every(primitive))return <ul className="list-disc space-y-1 pl-5 text-sm">{value.map((item,index)=><li key={index}>{display(item)}</li>)}</ul>;
  const keys=[...new Set(value.flatMap(item=>entries(item).filter(([,nested])=>primitive(nested)).map(([key])=>key)))];
  return <div className="space-y-4"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-navy-900 text-white"><tr>{keys.map(key=><th className="px-3 py-2 font-semibold" key={key}>{label(key)}</th>)}</tr></thead><tbody>{value.map((item,index)=><tr className="border-b border-slate-200" key={item?._id||index}>{keys.map(key=><td className="max-w-xs break-words px-3 py-2 align-top" key={key}>{display(item?.[key])}</td>)}</tr>)}</tbody></table></div>{value.map((item,index)=>entries(item).filter(([,nested])=>!primitive(nested)).map(([key,nested])=><div key={`${index}-${key}`} className="rounded-lg border border-slate-200 p-3"><h4 className="mb-2 text-sm font-bold text-brand-700">Record {index+1} — {label(key)}</h4><DataBlock value={nested}/></div>))}</div>;
}
