import {Router} from 'express';
import {Inquiry,User,Client,FollowUp,ActivityLog,Notification,DesignQuery,DesignTask,CostingSheet,Department,Role,MaterialRate,TaxSetting,SystemSetting} from '../models/index.js';
import {protect,authorize} from '../middleware/auth.js';
import {asyncHandler} from '../utils/http.js';
const router=Router();router.use(protect);
router.get('/dashboard',asyncHandler(async(req,res)=>{
  const now=new Date(),role=req.user.role?.name||req.user.roleName||'USER',terminal=['WON','LOST','CANCELLED','ARCHIVED'];
  const [inquiries,costings,followups,recent,users,queries,tasks]=await Promise.all([
    Inquiry.find({isDeleted:false}),CostingSheet.find(),FollowUp.find().sort({nextFollowUpDate:1}),ActivityLog.find().sort({createdAt:-1}).limit(8).populate('user','name'),User.find({isDeleted:false}),DesignQuery.find(),DesignTask.find()
  ]);
  const statusCounts=inquiries.reduce((out,x)=>{out[x.currentStatus]=(out[x.currentStatus]||0)+1;return out;},{}),count=(...statuses)=>statuses.reduce((sum,s)=>sum+(statusCounts[s]||0),0);
  const active=inquiries.filter(x=>!terminal.includes(x.currentStatus)).length;
  const overdue=inquiries.filter(x=>x.proposalSubmissionDate&&new Date(x.proposalSubmissionDate)<now&&!terminal.includes(x.currentStatus)&&x.currentStatus!=='SUBMITTED_TO_CLIENT').length;
  const values=costings.map(x=>Number(x.commercial?.finalQuotationAmount)||0),margins=costings.map(x=>Number(x.commercial?.profitMarginPercentage)).filter(Number.isFinite);
  const won=count('WON'),lost=count('LOST'),decided=won+lost;
  const metricsByRole={
    SALES:{newInquiries:count('DRAFT','ITF_CREATED'),underEstimation:count('SENT_TO_ESTIMATION','UNDER_ESTIMATION_REVIEW','JIF_IN_PROGRESS'),approvedProposals:count('GM_APPROVED','FORWARDED_TO_SALES'),pendingClientSubmissions:count('FORWARDED_TO_SALES','READY_FOR_CLIENT_SUBMISSION'),upcomingFollowUps:followups.filter(x=>x.nextFollowUpDate&&new Date(x.nextFollowUpDate)>=now).length,won,lost,conversionRate:decided?Number((won*100/decided).toFixed(1)):0},
    ESTIMATION:{newInquiriesReceived:count('SENT_TO_ESTIMATION'),pendingReviews:count('UNDER_ESTIMATION_REVIEW'),clarificationRequired:count('CLARIFICATION_REQUIRED'),jifsInProgress:count('JIF_IN_PROGRESS'),designsPending:count('SENT_TO_DESIGN','UNDER_DESIGN_REVIEW','DESIGN_IN_PROGRESS'),costingInProgress:count('RETURNED_TO_ESTIMATION','COSTING_IN_PROGRESS'),awaitingGm:count('PROPOSAL_PACKAGE_COMPLETED','SUBMITTED_TO_GM'),revisionRequired:count('GM_REVISION_REQUIRED','RETURNED_TO_ESTIMATION')},
    DESIGN:{newJifs:count('SENT_TO_DESIGN'),activeDesignJobs:tasks.filter(x=>['ACCEPTED','IN_PROGRESS'].includes(x.designStatus)).length,openQueries:queries.filter(x=>!['RESOLVED','CLOSED'].includes(x.status)).length,pendingClarifications:count('WAITING_FOR_DESIGN_CLARIFICATION'),completedDws:count('DWS_COMPLETED','RETURNED_TO_ESTIMATION'),overdueDesigns:tasks.filter(x=>x.targetDate&&new Date(x.targetDate)<now&&!['COMPLETED','RETURNED_TO_ESTIMATION'].includes(x.designStatus)).length},
    GM:{awaitingReview:count('SUBMITTED_TO_GM','UNDER_GM_REVIEW'),revisionRequired:count('GM_REVISION_REQUIRED'),approved:count('GM_APPROVED','FORWARDED_TO_SALES','SUBMITTED_TO_CLIENT'),rejected:count('GM_REJECTED'),highValue:costings.filter(x=>(Number(x.commercial?.finalQuotationAmount)||0)>=10000000).length,averageProfitMargin:margins.length?Number((margins.reduce((a,b)=>a+b,0)/margins.length).toFixed(2)):0},
    ADMIN:{totalUsers:users.length,activeUsers:users.filter(x=>x.isActive).length,activeInquiries:active,pendingApprovals:count('SUBMITTED_TO_GM','UNDER_GM_REVIEW'),auditEvents:await ActivityLog.countDocuments()}
  };
  res.json({success:true,data:{role,total:inquiries.length,active,overdue,statusCounts,totalQuotationValue:values.reduce((a,b)=>a+b,0),averageProfitMargin:margins.length?margins.reduce((a,b)=>a+b,0)/margins.length:0,upcomingFollowUps:followups.filter(x=>x.nextFollowUpDate&&new Date(x.nextFollowUpDate)>=now).slice(0,6),recentActivity:recent,roleMetrics:metricsByRole[role]||{}}});
}));
router.get('/reports/summary',asyncHandler(async(req,res)=>{const match={isDeleted:false};if(req.query.status)match.currentStatus=req.query.status;if(req.query.client)match.client=req.query.client;if(req.query.from||req.query.to)match.createdAt={...(req.query.from&&{$gte:new Date(req.query.from)}),...(req.query.to&&{$lte:new Date(req.query.to)})};const rows=await Inquiry.find(match).populate('client','companyName').populate('currentDepartment','name').sort({createdAt:-1});const aggregates=await Inquiry.aggregate([{$match:match},{$group:{_id:'$currentStatus',count:{$sum:1}}}]);res.json({success:true,data:{rows,aggregates}});}));
router.get('/reports/analytics',asyncHandler(async(req,res)=>{const [inquiries,costings,tasks,queries]=await Promise.all([Inquiry.find({isDeleted:false}).populate('client currentDepartment assignedTo'),CostingSheet.find(),DesignTask.find(),DesignQuery.find()]);const group=(items,key)=>items.reduce((out,x)=>{const raw=typeof x[key]==='object'?(x[key]?.name||x[key]?.companyName||'Unassigned'):(x[key]||'Unassigned');out[raw]=(out[raw]||0)+1;return out;},{});const now=Date.now(),ageing={under7:0,days8to30:0,days31to60:0,over60:0};for(const x of inquiries){const days=Math.floor((now-new Date(x.createdAt||now))/86400000);if(days<=7)ageing.under7++;else if(days<=30)ageing.days8to30++;else if(days<=60)ageing.days31to60++;else ageing.over60++;}const margins=costings.map(x=>Number(x.commercial?.profitMarginPercentage)).filter(Number.isFinite),values=costings.map(x=>Number(x.commercial?.finalQuotationAmount)||0);res.json({success:true,data:{byStatus:group(inquiries,'currentStatus'),byDepartment:group(inquiries,'currentDepartment'),byIndustry:inquiries.reduce((o,x)=>{const k=x.client?.industry||'Unspecified';o[k]=(o[k]||0)+1;return o;},{}),byLocation:group(inquiries,'projectLocation'),ageing,quotationValue:values.reduce((a,b)=>a+b,0),averageProfitMargin:margins.length?margins.reduce((a,b)=>a+b,0)/margins.length:0,designTurnaround:tasks.filter(x=>x.startDate&&x.actualCompletionDate).map(x=>({inquiry:x.inquiry,days:Math.ceil((new Date(x.actualCompletionDate)-new Date(x.startDate))/86400000)})),openQueryAgeing:queries.filter(x=>!['RESOLVED','CLOSED'].includes(x.status)).map(x=>({queryNumber:x.queryNumber,status:x.status,days:Math.floor((now-new Date(x.createdAt||now))/86400000)}))}});}));
router.get('/notifications',asyncHandler(async(req,res)=>res.json({success:true,data:await Notification.find({recipient:req.user._id}).sort({createdAt:-1}).limit(100)})));
router.patch('/notifications/:id/read',asyncHandler(async(req,res)=>res.json({success:true,data:await Notification.findOneAndUpdate({_id:req.params.id,recipient:req.user._id},{isRead:true},{new:true})})));
router.get('/queries',asyncHandler(async(req,res)=>{const filter={};if(req.query.status)filter.status=req.query.status;res.json({success:true,data:await DesignQuery.find(filter).populate('inquiry','inquiryNumber projectName').populate('raisedBy','name').sort({createdAt:-1})});}));
router.get('/settings',asyncHandler(async(req,res)=>{const [departments,roles,materialRates,taxes,settings]=await Promise.all([Department.find(),Role.find(),MaterialRate.find({isActive:true}),TaxSetting.find({isActive:true}),SystemSetting.find({isSecret:false})]);res.json({success:true,data:{departments,roles,materialRates,taxes,settings}});}));
router.post('/settings/material-rates',authorize('ADMIN'),asyncHandler(async(req,res)=>res.status(201).json({success:true,data:await MaterialRate.create(req.body)})));
router.post('/settings/taxes',authorize('ADMIN'),asyncHandler(async(req,res)=>res.status(201).json({success:true,data:await TaxSetting.create(req.body)})));
export default router;
