import {Router} from 'express';
import {Inquiry,User,Client,FollowUp,ActivityLog,Notification,DesignQuery,Department,Role,MaterialRate,TaxSetting,SystemSetting} from '../models/index.js';
import {protect,authorize} from '../middleware/auth.js';
import {asyncHandler} from '../utils/http.js';
const router=Router();router.use(protect);
router.get('/dashboard',asyncHandler(async(req,res)=>{const now=new Date(),role=req.user.role?.name||req.user.roleName||'USER',base={isDeleted:false};const [statusCounts,total,active,overdue,quotation,followups,recent]=await Promise.all([
  Inquiry.aggregate([{$match:base},{$group:{_id:'$currentStatus',count:{$sum:1}}}]),Inquiry.countDocuments(base),Inquiry.countDocuments({...base,currentStatus:{$nin:['WON','LOST','CANCELLED','ARCHIVED']}}),Inquiry.countDocuments({...base,proposalSubmissionDate:{$lt:now},currentStatus:{$nin:['WON','LOST','CANCELLED','ARCHIVED','SUBMITTED_TO_CLIENT']}}),Inquiry.aggregate([{$match:base},{$lookup:{from:'costingsheets',localField:'_id',foreignField:'inquiry',as:'costing'}},{$unwind:{path:'$costing',preserveNullAndEmptyArrays:true}},{$group:{_id:null,total:{$sum:'$costing.commercial.finalQuotationAmount'},avgMargin:{$avg:'$costing.commercial.profitMarginPercentage'}}}]),FollowUp.find({nextFollowUpDate:{$gte:now}}).sort({nextFollowUpDate:1}).limit(6).populate('inquiry','inquiryNumber projectName'),ActivityLog.find().sort({timestamp:-1}).limit(8).populate('user','name')
]);res.json({success:true,data:{role,total,active,overdue,statusCounts:Object.fromEntries(statusCounts.map(x=>[x._id,x.count])),totalQuotationValue:quotation[0]?.total||0,averageProfitMargin:quotation[0]?.avgMargin||0,upcomingFollowUps:followups,recentActivity:recent}});}));
router.get('/reports/summary',asyncHandler(async(req,res)=>{const match={isDeleted:false};if(req.query.status)match.currentStatus=req.query.status;if(req.query.client)match.client=req.query.client;if(req.query.from||req.query.to)match.createdAt={...(req.query.from&&{$gte:new Date(req.query.from)}),...(req.query.to&&{$lte:new Date(req.query.to)})};const rows=await Inquiry.find(match).populate('client','companyName').populate('currentDepartment','name').sort({createdAt:-1});const aggregates=await Inquiry.aggregate([{$match:match},{$group:{_id:'$currentStatus',count:{$sum:1}}}]);res.json({success:true,data:{rows,aggregates}});}));
router.get('/notifications',asyncHandler(async(req,res)=>res.json({success:true,data:await Notification.find({recipient:req.user._id}).sort({createdAt:-1}).limit(100)})));
router.patch('/notifications/:id/read',asyncHandler(async(req,res)=>res.json({success:true,data:await Notification.findOneAndUpdate({_id:req.params.id,recipient:req.user._id},{isRead:true},{new:true})})));
router.get('/queries',asyncHandler(async(req,res)=>{const filter={};if(req.query.status)filter.status=req.query.status;res.json({success:true,data:await DesignQuery.find(filter).populate('inquiry','inquiryNumber projectName').populate('raisedBy','name').sort({createdAt:-1})});}));
router.get('/settings',asyncHandler(async(req,res)=>{const [departments,roles,materialRates,taxes,settings]=await Promise.all([Department.find(),Role.find(),MaterialRate.find({isActive:true}),TaxSetting.find({isActive:true}),SystemSetting.find({isSecret:false})]);res.json({success:true,data:{departments,roles,materialRates,taxes,settings}});}));
router.post('/settings/material-rates',authorize('ADMIN'),asyncHandler(async(req,res)=>res.status(201).json({success:true,data:await MaterialRate.create(req.body)})));
router.post('/settings/taxes',authorize('ADMIN'),asyncHandler(async(req,res)=>res.status(201).json({success:true,data:await TaxSetting.create(req.body)})));
export default router;
