import {Router} from 'express';
import {Inquiry,Client,InquiryTakingForm,ActivityLog,Document,JobInquiryForm,DesignWeightSummary,CostingSheet,CommercialProposal,TechnicalProposal,ProposalDrawing,GMReview,SalesSubmission,FollowUp,DesignTask,DesignQuery} from '../models/index.js';
import {protect,authorize} from '../middleware/auth.js';
import {asyncHandler,AppError,parsePagination} from '../utils/http.js';
import {transitionInquiry,createRevision} from '../services/workflowService.js';
import {audit} from '../services/auditService.js';
const router=Router();router.use(protect);
async function nextNumber(){const d=new Date(),prefix=`IQN-${String(d.getFullYear()).slice(-2)}-${String(d.getMonth()+1).padStart(2,'0')}`;const last=await Inquiry.findOne({inquiryNumber:{$regex:`^${prefix}-`}}).sort({inquiryNumber:-1}).select('inquiryNumber');const seq=last?Number(last.inquiryNumber.split('-').at(-1))+1:1;return `${prefix}-${String(seq).padStart(3,'0')}`;}
router.get('/',asyncHandler(async(req,res)=>{const {page,limit,skip}=parsePagination(req.query),filter={isDeleted:false};for(const key of ['currentStatus','client','currentDepartment','assignedTo','urgency'])if(req.query[key])filter[key]=req.query[key];if(req.query.search)filter.$text={$search:req.query.search};if(req.query.from||req.query.to)filter.createdAt={...(req.query.from&&{$gte:new Date(req.query.from)}),...(req.query.to&&{$lte:new Date(req.query.to)})};const [items,total]=await Promise.all([Inquiry.find(filter).populate('client','companyName clientCode').populate('currentDepartment assignedTo').sort({updatedAt:-1}).skip(skip).limit(limit),Inquiry.countDocuments(filter)]);res.json({success:true,data:items,meta:{page,limit,total,pages:Math.ceil(total/limit)}});}));
router.post('/',authorize('ADMIN','SALES'),asyncHandler(async(req,res)=>{if(!req.body?.client)throw new AppError('Client ID is required',422);if(!await Client.exists({_id:req.body.client,isDeleted:false,status:'ACTIVE'}))throw new AppError('Active client required',422);const inquiry=await Inquiry.create({...req.body,inquiryNumber:await nextNumber(),createdBy:req.user._id,currentStatus:'DRAFT'});await audit(req,{action:'CREATE',entityType:'Inquiry',entityId:inquiry._id,newValue:inquiry});res.status(201).json({success:true,data:inquiry});}));
router.get('/:id',asyncHandler(async(req,res)=>{const item=await Inquiry.findOne({_id:req.params.id,isDeleted:false}).populate('client currentDepartment assignedTo createdBy');if(!item)throw new AppError('Inquiry not found',404);res.json({success:true,data:item});}));
router.put('/:id',authorize('ADMIN','SALES'),asyncHandler(async(req,res)=>{const item=await Inquiry.findById(req.params.id);if(!item)throw new AppError('Inquiry not found',404);if(!['DRAFT','ITF_CREATED'].includes(item.currentStatus))throw new AppError('Only draft inquiries can be edited',409);Object.assign(item,req.body);await item.save();await audit(req,{action:'UPDATE',entityType:'Inquiry',entityId:item._id,newValue:item});res.json({success:true,data:item});}));
router.delete('/:id',authorize('ADMIN'),asyncHandler(async(req,res)=>{await Inquiry.findByIdAndUpdate(req.params.id,{isDeleted:true,deletedAt:new Date()});res.json({success:true});}));
router.patch('/:id/status',asyncHandler(async(req,res)=>{const old=await Inquiry.findById(req.params.id);const item=await transitionInquiry({inquiryId:req.params.id,to:req.body.status,user:req.user,comments:req.body.comments,returnDepartment:req.body.returnDepartment});await audit(req,{action:'STATUS_CHANGE',entityType:'Inquiry',entityId:item._id,oldValue:{status:old.currentStatus},newValue:{status:item.currentStatus},description:req.body.comments});res.json({success:true,data:item});}));
router.post('/:id/revision',asyncHandler(async(req,res)=>res.status(201).json({success:true,data:await createRevision(req.params.id,req.user,req.body.reason)})));
router.get('/:id/timeline',asyncHandler(async(req,res)=>{const items=await ActivityLog.find({entityId:req.params.id}).populate('user','name').sort({timestamp:-1});res.json({success:true,data:items});}));
router.get('/:id/package',asyncHandler(async(req,res)=>{const inquiry=await Inquiry.findById(req.params.id).populate('client');if(!inquiry)throw new AppError('Inquiry not found',404);const f={inquiry:inquiry._id,revision:inquiry.packageLocked?inquiry.approvedRevision:inquiry.revisionNumber};const [itf,jif,dws,costing,commercial,technical,drawings,review,documents]=await Promise.all([InquiryTakingForm.findOne({inquiry:inquiry._id}),JobInquiryForm.findOne(f),DesignWeightSummary.findOne(f),CostingSheet.findOne(f),CommercialProposal.findOne(f),TechnicalProposal.findOne(f),ProposalDrawing.find(f),GMReview.findOne({inquiry:inquiry._id}),Document.find({inquiryId:inquiry._id,status:'ACTIVE'})]);res.json({success:true,data:{inquiry,itf,jif,dws,costing,commercial,technical,drawings,review,documents}});}));
router.post('/:id/duplicate',authorize('ADMIN','SALES'),asyncHandler(async(req,res)=>{const src=await Inquiry.findById(req.params.id).lean();if(!src)throw new AppError('Inquiry not found',404);delete src._id;delete src.createdAt;delete src.updatedAt;delete src.__v;const copy=await Inquiry.create({...src,inquiryNumber:await nextNumber(),projectName:`${src.projectName} (Copy)`,revisionNumber:0,currentStatus:'DRAFT',packageLocked:false,approvedRevision:undefined,createdBy:req.user._id});res.status(201).json({success:true,data:copy});}));
export default router;
