import {Router} from 'express';
import {Inquiry,InquiryTakingForm,JobInquiryForm,DesignTask,DesignQuery,DesignWeightSummary,CostingSheet,CommercialProposal,TechnicalProposal,ProposalDrawing,GMReview,SalesSubmission,FollowUp,Document,Notification,User} from '../models/index.js';
import {protect,authorize} from '../middleware/auth.js';
import {asyncHandler,AppError} from '../utils/http.js';
import {transitionInquiry,assertUnlocked} from '../services/workflowService.js';
import {calculateCosting} from '../services/costingService.js';
import {audit} from '../services/auditService.js';
import {upload} from '../middleware/upload.js';
const router=Router();router.use(protect);
const inquiry=async id=>{const x=await Inquiry.findById(id);if(!x)throw new AppError('Inquiry not found',404);return x;};
const role=r=>(...args)=>authorize(...r)(...args);
const current=async(Model,id)=>{const i=await inquiry(id);return {i,doc:await Model.findOne({inquiry:i._id,revision:i.revisionNumber})};};

// Inquiry Taking Form
router.post('/inquiries/:id/itf',role(['ADMIN','SALES']),asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id);if(!['DRAFT','ITF_CREATED'].includes(i.currentStatus))throw new AppError('ITF cannot be created at this stage',409);const doc=await InquiryTakingForm.findOneAndUpdate({inquiry:i._id},{$set:{...req.body,createdBy:req.user._id},$setOnInsert:{revision:i.revisionNumber}},{upsert:true,new:true,runValidators:true});if(i.currentStatus==='DRAFT')await transitionInquiry({inquiryId:i._id,to:'ITF_CREATED',user:req.user});res.status(201).json({success:true,data:doc});}));
router.get('/inquiries/:id/itf',asyncHandler(async(req,res)=>res.json({success:true,data:await InquiryTakingForm.findOne({inquiry:req.params.id})})));
router.put('/inquiries/:id/itf',role(['ADMIN','SALES']),asyncHandler(async(req,res)=>{const doc=await InquiryTakingForm.findOne({inquiry:req.params.id});if(!doc)throw new AppError('ITF not found',404);if(doc.status==='SUBMITTED')throw new AppError('Submitted ITF cannot be changed until returned',409);Object.assign(doc,req.body);await doc.save();res.json({success:true,data:doc});}));
router.post('/inquiries/:id/itf/submit',role(['ADMIN','SALES']),asyncHandler(async(req,res)=>{const doc=await InquiryTakingForm.findOne({inquiry:req.params.id});if(!doc)throw new AppError('ITF is required',422);doc.status='SUBMITTED';doc.submittedAt=new Date();await doc.save();const i=await transitionInquiry({inquiryId:req.params.id,to:'SENT_TO_ESTIMATION',user:req.user});await audit(req,{action:'FORM_SUBMISSION',entityType:'Inquiry',entityId:i._id,description:'ITF submitted to Estimation'});res.json({success:true,data:{itf:doc,inquiry:i}});}));

// Estimation clarification and JIF
router.post('/inquiries/:id/estimation/accept',role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{let i=await inquiry(req.params.id);if(i.currentStatus==='SENT_TO_ESTIMATION')i=await transitionInquiry({inquiryId:i._id,to:'UNDER_ESTIMATION_REVIEW',user:req.user});i=await transitionInquiry({inquiryId:i._id,to:'JIF_IN_PROGRESS',user:req.user});res.json({success:true,data:i});}));
router.post('/inquiries/:id/design-queries',role(['ADMIN','ESTIMATION','DESIGN']),asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id),type=(req.user.role?.name||req.user.roleName)==='DESIGN'?'DESIGN':'ESTIMATION';const count=await DesignQuery.countDocuments({inquiry:i._id});const q=await DesignQuery.create({...req.body,inquiry:i._id,queryNumber:`${i.inquiryNumber}-Q-${String(count+1).padStart(2,'0')}`,raisedBy:req.user._id,type,status:req.body.status||'OPEN',raisedAt:new Date(),history:[{action:'RAISED',status:'OPEN',changedBy:req.user._id,changedAt:new Date()}]});const target=type==='DESIGN'?'DESIGN_QUERY_RAISED':'CLARIFICATION_REQUIRED';if((await inquiry(i._id)).currentStatus!==target)await transitionInquiry({inquiryId:i._id,to:target,user:req.user});if(type==='DESIGN')await transitionInquiry({inquiryId:i._id,to:'WAITING_FOR_DESIGN_CLARIFICATION',user:req.user});res.status(201).json({success:true,data:q});}));
router.get('/inquiries/:id/design-queries',asyncHandler(async(req,res)=>res.json({success:true,data:await DesignQuery.find({inquiry:req.params.id}).populate('raisedBy assignedTo assignedDepartment').sort({createdAt:-1})})));
router.post('/design-queries/:id/respond',asyncHandler(async(req,res)=>{const q=await DesignQuery.findById(req.params.id);if(!q)throw new AppError('Query not found',404);q.response=req.body.response;q.status='RESPONDED';q.respondedAt=new Date();q.history=[...(q.history||[]),{action:'RESPONDED',status:'RESPONDED',comments:req.body.response,changedBy:req.user._id,changedAt:new Date()}];await q.save();const i=await inquiry(q.inquiry);const to=q.type==='DESIGN'?'DESIGN_IN_PROGRESS':'CLARIFICATION_RECEIVED';await transitionInquiry({inquiryId:i._id,to,user:req.user});res.json({success:true,data:q});}));
router.post('/design-queries/:id/resolve',asyncHandler(async(req,res)=>{const q=await DesignQuery.findById(req.params.id);if(!q)throw new AppError('Query not found',404);q.status='RESOLVED';q.resolvedAt=new Date();q.history=[...(q.history||[]),{action:'RESOLVED',status:'RESOLVED',comments:req.body.comments,changedBy:req.user._id,changedAt:new Date()}];await q.save();res.json({success:true,data:q});}));
router.patch('/design-queries/:id',asyncHandler(async(req,res)=>{const q=await DesignQuery.findById(req.params.id);if(!q)throw new AppError('Query not found',404);const allowed=['title','description','priority','assignedTo','assignedDepartment','status'];for(const key of allowed)if(req.body[key]!==undefined)q[key]=req.body[key];q.history=[...(q.history||[]),{action:'UPDATED',status:q.status,comments:req.body.comments,changedBy:req.user._id,changedAt:new Date()}];await q.save();res.json({success:true,data:q});}));
router.post('/design-queries/:id/reopen',asyncHandler(async(req,res)=>{const q=await DesignQuery.findById(req.params.id);if(!q)throw new AppError('Query not found',404);if(q.status!=='RESOLVED')throw new AppError('Only resolved queries can be reopened',409);q.status='REOPENED';q.reopenedAt=new Date();q.history=[...(q.history||[]),{action:'REOPENED',comments:req.body.comments,changedBy:req.user._id,changedAt:new Date()}];await q.save();res.json({success:true,data:q});}));
router.get('/design-queries/:id/history',asyncHandler(async(req,res)=>{const q=await DesignQuery.findById(req.params.id);if(!q)throw new AppError('Query not found',404);res.json({success:true,data:q.history||[]});}));
router.post('/inquiries/:id/jif',role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id);if(i.packageLocked)throw new AppError('Create a revision before editing the approved package',423);const doc=await JobInquiryForm.findOneAndUpdate({inquiry:i._id,revision:i.revisionNumber},{$set:{...req.body,createdBy:req.user._id}},{upsert:true,new:true,runValidators:true});res.status(201).json({success:true,data:doc});}));
router.get('/inquiries/:id/jif',asyncHandler(async(req,res)=>{const {i,doc}=await current(JobInquiryForm,req.params.id);res.json({success:true,data:doc});}));
router.put('/inquiries/:id/jif',role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{const {doc}=await current(JobInquiryForm,req.params.id);if(!doc)throw new AppError('JIF not found',404);assertUnlocked(doc);Object.assign(doc,req.body);await doc.save();res.json({success:true,data:doc});}));
router.post('/inquiries/:id/jif/revision',role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id),prior=await JobInquiryForm.findOne({inquiry:i._id}).sort({revision:-1}).lean();if(!prior)throw new AppError('JIF not found',404);delete prior._id;delete prior.__v;delete prior.createdAt;delete prior.updatedAt;const doc=await JobInquiryForm.create({...prior,revision:prior.revision+1,revisionCause:req.body.revisionCause,status:'DRAFT',isLocked:false,createdBy:req.user._id});res.status(201).json({success:true,data:doc});}));
router.post('/inquiries/:id/jif/submit-to-design',role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{const {i,doc}=await current(JobInquiryForm,req.params.id);if(!doc)throw new AppError('JIF not found',422);assertUnlocked(doc);doc.status='SUBMITTED';doc.submittedAt=new Date();await doc.save();let state=i;if(state.currentStatus==='JIF_IN_PROGRESS')state=await transitionInquiry({inquiryId:i._id,to:'JIF_COMPLETED',user:req.user});state=await transitionInquiry({inquiryId:i._id,to:'SENT_TO_DESIGN',user:req.user});const task=await DesignTask.findOneAndUpdate({inquiry:i._id},{$setOnInsert:{assignedBy:req.user._id,priority:i.priority,targetDate:i.designRequiredDate}},{upsert:true,new:true});res.json({success:true,data:{jif:doc,task,inquiry:state}});}));

// Design task and DWS
router.post('/inquiries/:id/design-task',role(['ADMIN','ESTIMATION','DESIGN']),asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id);const task=await DesignTask.findOneAndUpdate({inquiry:i._id},{$set:{...req.body,assignedBy:req.user._id}},{upsert:true,new:true,runValidators:true});res.status(201).json({success:true,data:task});}));
router.get('/inquiries/:id/design-task',asyncHandler(async(req,res)=>res.json({success:true,data:await DesignTask.findOne({inquiry:req.params.id}).populate('assignedDesigner assignedBy')})));
router.put('/design-tasks/:id',role(['ADMIN','DESIGN']),asyncHandler(async(req,res)=>{const task=await DesignTask.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!task)throw new AppError('Design task not found',404);const i=await inquiry(task.inquiry);if(i.currentStatus==='SENT_TO_DESIGN')await transitionInquiry({inquiryId:i._id,to:'UNDER_DESIGN_REVIEW',user:req.user});if(req.body.designStatus==='IN_PROGRESS'&&(await inquiry(i._id)).currentStatus==='UNDER_DESIGN_REVIEW')await transitionInquiry({inquiryId:i._id,to:'DESIGN_IN_PROGRESS',user:req.user});res.json({success:true,data:task});}));
router.post('/inquiries/:id/dws',role(['ADMIN','DESIGN']),asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id);const buildings=(req.body.buildings||[]).map(b=>{const total=['mainFrameWeight','secondarySteelWeight','bracingWeight','claddingWeight','accessoriesWeight','canopyWeight','miscellaneousWeight'].reduce((s,k)=>s+(Number(b[k])||0),0);return {...b,totalSteelWeight:total,weightPerSquareFoot:b.buildingArea?total/b.buildingArea:0,weightPerSquareMeter:b.buildingArea?total/(b.buildingArea*0.092903):0};});const doc=await DesignWeightSummary.findOneAndUpdate({inquiry:i._id,revision:i.revisionNumber},{$set:{...req.body,buildings,preparedBy:req.user._id}},{upsert:true,new:true,runValidators:true});res.status(201).json({success:true,data:doc});}));
router.get('/inquiries/:id/dws',asyncHandler(async(req,res)=>res.json({success:true,data:(await current(DesignWeightSummary,req.params.id)).doc})));
router.put('/inquiries/:id/dws',role(['ADMIN','DESIGN']),asyncHandler(async(req,res)=>{const {doc}=await current(DesignWeightSummary,req.params.id);if(!doc)throw new AppError('DWS not found',404);assertUnlocked(doc);Object.assign(doc,req.body);await doc.save();res.json({success:true,data:doc});}));
router.post('/inquiries/:id/dws/submit',role(['ADMIN','DESIGN']),asyncHandler(async(req,res)=>{const {i,doc}=await current(DesignWeightSummary,req.params.id);if(!doc||!doc.buildings.length)throw new AppError('At least one building is required',422);doc.status='SUBMITTED';doc.completionDate=new Date();await doc.save();let state=i;if(state.currentStatus==='DESIGN_IN_PROGRESS')state=await transitionInquiry({inquiryId:i._id,to:'DWS_COMPLETED',user:req.user});state=await transitionInquiry({inquiryId:i._id,to:'RETURNED_TO_ESTIMATION',user:req.user,comments:doc.remarks||'DWS completed and returned to Estimation'});await DesignTask.findOneAndUpdate({inquiry:i._id},{designStatus:'RETURNED_TO_ESTIMATION',actualCompletionDate:new Date()});res.json({success:true,data:{dws:doc,inquiry:state}});}));

// Costing and proposals
router.post('/inquiries/:id/costing',role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id);if(i.currentStatus==='RETURNED_TO_ESTIMATION')await transitionInquiry({inquiryId:i._id,to:'COSTING_IN_PROGRESS',user:req.user});const calculated=calculateCosting(req.body);const doc=await CostingSheet.findOneAndUpdate({inquiry:i._id,revision:i.revisionNumber},{$set:{...calculated,createdBy:req.user._id}},{upsert:true,new:true,runValidators:true});res.status(201).json({success:true,data:doc});}));
router.get('/inquiries/:id/costing',asyncHandler(async(req,res)=>res.json({success:true,data:(await current(CostingSheet,req.params.id)).doc})));
router.put('/inquiries/:id/costing',role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{const {doc}=await current(CostingSheet,req.params.id);if(!doc)throw new AppError('Costing not found',404);assertUnlocked(doc);Object.assign(doc,calculateCosting(req.body));await doc.save();res.json({success:true,data:doc});}));
router.post('/inquiries/:id/costing/calculate',role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>res.json({success:true,data:calculateCosting(req.body)})));
router.post('/inquiries/:id/costing/complete',role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{const {i,doc}=await current(CostingSheet,req.params.id);if(!doc)throw new AppError('Costing not found',422);doc.status='COMPLETED';await doc.save();const state=await transitionInquiry({inquiryId:i._id,to:'COSTING_COMPLETED',user:req.user});res.json({success:true,data:{costing:doc,inquiry:state}});}));
for(const [path,Model,status] of [['commercial-proposal',CommercialProposal,'COMMERCIAL_PROPOSAL_PREPARED'],['technical-proposal',TechnicalProposal,'TECHNICAL_PROPOSAL_PREPARED']]){
  router.post(`/inquiries/:id/${path}`,role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id);const doc=await Model.findOneAndUpdate({inquiry:i._id,revision:i.revisionNumber},{$set:{...req.body,createdBy:req.user._id}},{upsert:true,new:true,runValidators:true});res.status(201).json({success:true,data:doc});}));
  router.get(`/inquiries/:id/${path}`,asyncHandler(async(req,res)=>res.json({success:true,data:(await current(Model,req.params.id)).doc})));
  router.put(`/inquiries/:id/${path}`,role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{const {doc}=await current(Model,req.params.id);if(!doc)throw new AppError('Proposal not found',404);assertUnlocked(doc);Object.assign(doc,req.body);await doc.save();res.json({success:true,data:doc});}));
  router.post(`/inquiries/:id/${path}/complete`,role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{const {i,doc}=await current(Model,req.params.id);if(!doc)throw new AppError('Proposal not found',422);doc.status='COMPLETED';await doc.save();const state=await transitionInquiry({inquiryId:i._id,to:status,user:req.user});res.json({success:true,data:{proposal:doc,inquiry:state}});}));
}
router.post('/inquiries/:id/drawings',role(['ADMIN','ESTIMATION','DESIGN']),asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id);const doc=await ProposalDrawing.create({...req.body,inquiry:i._id,revision:i.revisionNumber,createdBy:req.user._id});res.status(201).json({success:true,data:doc});}));
router.get('/inquiries/:id/drawings',asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id);res.json({success:true,data:await ProposalDrawing.find({inquiry:i._id}).populate('document').sort({drawingNumber:1,revision:-1})});}));
router.post('/inquiries/:id/package/complete',role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id);const drawings=await ProposalDrawing.find({inquiry:i._id,revision:i.revisionNumber});if(!drawings.length)throw new AppError('At least one proposal drawing is required',422);await ProposalDrawing.updateMany({_id:{$in:drawings.map(x=>x._id)}},{status:'COMPLETED'});const state=await transitionInquiry({inquiryId:i._id,to:'PROPOSAL_PACKAGE_COMPLETED',user:req.user});res.json({success:true,data:state});}));
router.post('/inquiries/:id/package/submit-to-gm',role(['ADMIN','ESTIMATION']),asyncHandler(async(req,res)=>{const state=await transitionInquiry({inquiryId:req.params.id,to:'SUBMITTED_TO_GM',user:req.user});res.json({success:true,data:state});}));

// GM review
router.post('/inquiries/:id/gm-review',role(['ADMIN','GM']),asyncHandler(async(req,res)=>{let i=await inquiry(req.params.id);if(i.currentStatus==='SUBMITTED_TO_GM')i=await transitionInquiry({inquiryId:i._id,to:'UNDER_GM_REVIEW',user:req.user});const review=await GMReview.findOneAndUpdate({inquiry:i._id},{$set:{...req.body,reviewedBy:req.user._id,reviewDate:new Date()}},{upsert:true,new:true});res.status(201).json({success:true,data:review});}));
router.get('/inquiries/:id/gm-review',asyncHandler(async(req,res)=>res.json({success:true,data:await GMReview.findOne({inquiry:req.params.id}).populate('reviewedBy')})));
router.post('/inquiries/:id/gm-review/approve',role(['ADMIN','GM']),asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id);const review=await GMReview.findOneAndUpdate({inquiry:i._id},{$set:{decision:'APPROVED',comments:req.body.comments,reviewedBy:req.user._id,reviewDate:new Date(),approvalNumber:`APR-${Date.now()}`,approvedRevision:i.revisionNumber,snapshot:req.body.snapshot}},{upsert:true,new:true});const state=await transitionInquiry({inquiryId:i._id,to:'GM_APPROVED',user:req.user});res.json({success:true,data:{review,inquiry:state}});}));
router.post('/inquiries/:id/gm-review/request-revision',role(['ADMIN','GM']),asyncHandler(async(req,res)=>{if(!req.body.comments?.trim())throw new AppError('Revision comments are required',422);const i=await inquiry(req.params.id);const decision=req.body.department==='Design'?'RETURNED_TO_DESIGN':'RETURNED_TO_ESTIMATION';const review=await GMReview.findOneAndUpdate({inquiry:i._id},{$set:{decision:'REVISION_REQUIRED',comments:req.body.comments,reviewedBy:req.user._id,reviewDate:new Date()}},{upsert:true,new:true});let state=await transitionInquiry({inquiryId:i._id,to:'GM_REVISION_REQUIRED',user:req.user,comments:req.body.comments});state=await transitionInquiry({inquiryId:i._id,to:decision,user:req.user,comments:req.body.comments});res.json({success:true,data:{review,inquiry:state}});}));
router.post('/inquiries/:id/gm-review/reject',role(['ADMIN','GM']),asyncHandler(async(req,res)=>{if(!req.body.comments?.trim())throw new AppError('Rejection comments are required',422);await GMReview.findOneAndUpdate({inquiry:req.params.id},{$set:{decision:'REJECTED',comments:req.body.comments,reviewedBy:req.user._id,reviewDate:new Date()}},{upsert:true});res.json({success:true,data:await transitionInquiry({inquiryId:req.params.id,to:'GM_REJECTED',user:req.user,comments:req.body.comments})});}));
router.post('/inquiries/:id/gm-review/forward-to-sales',role(['ADMIN','GM']),asyncHandler(async(req,res)=>{const state=await transitionInquiry({inquiryId:req.params.id,to:'FORWARDED_TO_SALES',user:req.user});await GMReview.findOneAndUpdate({inquiry:req.params.id},{forwardedToSales:true,forwardedDate:new Date()});res.json({success:true,data:state});}));

// Sales submission, followups and outcome
router.post('/inquiries/:id/client-submission',role(['ADMIN','SALES']),asyncHandler(async(req,res)=>{let i=await inquiry(req.params.id);if(i.currentStatus==='FORWARDED_TO_SALES')i=await transitionInquiry({inquiryId:i._id,to:'READY_FOR_CLIENT_SUBMISSION',user:req.user});i=await transitionInquiry({inquiryId:i._id,to:'SUBMITTED_TO_CLIENT',user:req.user});const doc=await SalesSubmission.findOneAndUpdate({inquiry:i._id},{$set:{...req.body,submittedBy:req.user._id,submissionDate:req.body.submissionDate||new Date(),proposalReceivedDate:i.approvedAt}},{upsert:true,new:true});res.status(201).json({success:true,data:{submission:doc,inquiry:i}});}));
router.get('/inquiries/:id/client-submission',asyncHandler(async(req,res)=>res.json({success:true,data:await SalesSubmission.findOne({inquiry:req.params.id})})));
router.post('/inquiries/:id/follow-ups',role(['ADMIN','SALES']),asyncHandler(async(req,res)=>{let i=await inquiry(req.params.id);if(i.currentStatus==='SUBMITTED_TO_CLIENT')i=await transitionInquiry({inquiryId:i._id,to:'CLIENT_REVIEWING',user:req.user});if(i.currentStatus==='CLIENT_REVIEWING'&&req.body.nextFollowUpDate)i=await transitionInquiry({inquiryId:i._id,to:'FOLLOW_UP_REQUIRED',user:req.user});const doc=await FollowUp.create({...req.body,inquiry:req.params.id,createdBy:req.user._id});res.status(201).json({success:true,data:doc});}));
router.get('/inquiries/:id/follow-ups',asyncHandler(async(req,res)=>res.json({success:true,data:await FollowUp.find({inquiry:req.params.id}).populate('createdBy','name').sort({followUpDate:-1})})));
router.patch('/inquiries/:id/final-status',role(['ADMIN','SALES']),asyncHandler(async(req,res)=>{const {status}=req.body;if(status==='LOST'&&!req.body.lostReason)throw new AppError('Lost reason is required',422);if(status==='WON'&&(!req.body.finalAgreedValue||!req.body.awardDate||!req.body.purchaseOrderNumber||!req.body.expectedProjectStartDate))throw new AppError('Won details and purchase order are required',422);const i=await inquiry(req.params.id);i.finalResult=req.body;await i.save();const state=await transitionInquiry({inquiryId:i._id,to:status,user:req.user});res.json({success:true,data:state});}));

// Central documents
router.post('/inquiries/:id/documents',upload.array('files',10),asyncHandler(async(req,res)=>{const i=await inquiry(req.params.id);if(i.packageLocked)throw new AppError('Approved package documents are locked',423);const count=await Document.countDocuments({inquiryId:i._id});const docs=await Document.insertMany(req.files.map((f,index)=>({inquiryId:i._id,documentType:req.body.documentType||'Other',documentNumber:`${i.inquiryNumber}-DOC-${String(count+index+1).padStart(3,'0')}`,title:req.body.title||f.originalname,revision:i.revisionNumber,versionNumber:1,fileName:f.originalname,filePath:f.path,mimeType:f.mimetype,fileSize:f.size,status:'ACTIVE',uploadedBy:req.user._id,remarks:req.body.remarks})));res.status(201).json({success:true,data:docs});}));
router.get('/inquiries/:id/documents',asyncHandler(async(req,res)=>res.json({success:true,data:await Document.find({inquiryId:req.params.id,status:{$ne:'DELETED'}}).populate('uploadedBy','name').sort({createdAt:-1})})));
router.get('/documents',asyncHandler(async(req,res)=>{const filter={status:{$ne:'DELETED'}};if(req.query.documentType)filter.documentType=req.query.documentType;if(req.query.inquiryId)filter.inquiryId=req.query.inquiryId;res.json({success:true,data:await Document.find(filter).populate('uploadedBy inquiryId').sort({createdAt:-1}).limit(200)});}));
router.post('/documents/:id/replace',upload.single('file'),asyncHandler(async(req,res)=>{const old=await Document.findById(req.params.id);if(!old||old.status==='DELETED')throw new AppError('Document not found',404);if(old.isLocked)throw new AppError('Locked document cannot be replaced',423);if(!req.file)throw new AppError('Replacement file is required',422);old.status='SUPERSEDED';await old.save();const replacement=await Document.create({inquiryId:old.inquiryId,documentType:old.documentType,documentNumber:old.documentNumber,title:req.body.title||old.title,revision:old.revision,versionNumber:(Number(old.versionNumber)||1)+1,previousVersion:old._id,fileName:req.file.originalname,filePath:req.file.path,mimeType:req.file.mimetype,fileSize:req.file.size,status:'ACTIVE',uploadedBy:req.user._id,remarks:req.body.remarks||old.remarks});res.status(201).json({success:true,data:replacement});}));
router.delete('/documents/:id',asyncHandler(async(req,res)=>{const doc=await Document.findById(req.params.id);if(!doc)throw new AppError('Document not found',404);if(doc.isLocked)throw new AppError('Locked document cannot be deleted',423);doc.status='DELETED';await doc.save();res.json({success:true});}));
router.get('/documents/:id/download',asyncHandler(async(req,res)=>{const doc=await Document.findById(req.params.id);if(!doc||doc.status==='DELETED')throw new AppError('Document not found',404);res.download(doc.filePath,doc.fileName);}));
router.get('/documents/:id/preview',asyncHandler(async(req,res)=>{const doc=await Document.findById(req.params.id);if(!doc||doc.status==='DELETED')throw new AppError('Document not found',404);res.type(doc.mimeType||'application/octet-stream');res.setHeader('Content-Disposition',`inline; filename="${String(doc.fileName).replaceAll('"','')}"`);res.sendFile(doc.filePath);}));
export default router;
