import {useState} from 'react';import {NavLink,Outlet,useLocation,useNavigate} from 'react-router-dom';import {LayoutDashboard,Building2,ClipboardList,MessageSquareText,Bell,BarChart3,Users,Settings,UserRound,LogOut,Menu,X,ChevronRight,HardHat,FolderOpen,ScrollText,SlidersHorizontal} from 'lucide-react';import {useAuth} from '../context/AuthContext';
const items=[
  {to:'/dashboard',label:'Dashboard',icon:LayoutDashboard,roles:['ADMIN','SALES','ESTIMATION','DESIGN','GM']},
  {to:'/clients',label:'Clients',icon:Building2,roles:['ADMIN','SALES','ESTIMATION','GM']},
  {to:'/inquiries',label:'Inquiries',icon:ClipboardList,roles:['ADMIN','SALES','ESTIMATION','DESIGN','GM']},
  {to:'/queries',label:'Queries',icon:MessageSquareText,roles:['ADMIN','SALES','ESTIMATION','DESIGN']},
  {to:'/documents',label:'Documents',icon:FolderOpen,roles:['ADMIN','SALES','ESTIMATION','DESIGN','GM']},
  {to:'/notifications',label:'Notifications',icon:Bell,roles:['ADMIN','SALES','ESTIMATION','DESIGN','GM']},
  {to:'/reports',label:'Reports',icon:BarChart3,roles:['ADMIN','SALES','ESTIMATION','GM']},
  {to:'/analytics',label:'Analytics',icon:BarChart3,roles:['ADMIN','SALES','ESTIMATION','GM']},
  {to:'/users',label:'Users',icon:Users,roles:['ADMIN']},{to:'/audit-logs',label:'Audit logs',icon:ScrollText,roles:['ADMIN']},{to:'/administration',label:'Administration',icon:SlidersHorizontal,roles:['ADMIN']},{to:'/settings',label:'Settings',icon:Settings,roles:['ADMIN']}
];
export default function AppLayout(){const [open,setOpen]=useState(false),{user,logout}=useAuth(),location=useLocation(),navigate=useNavigate();const nav=items.filter(x=>x.roles.includes(user?.role?.name));const title=nav.find(x=>location.pathname.startsWith(x.to))?.label||'Workspace';return <div className="min-h-screen bg-slate-50"><aside className={`fixed inset-y-0 left-0 z-40 w-64 bg-navy-950 text-white transition-transform lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}><div className="flex h-18 items-center gap-3 border-b border-white/10 px-5 py-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-brand-500"><HardHat size={22}/></div><div><div className="font-bold tracking-wide">RT INQUIRY</div><div className="text-[11px] text-blue-200">PROPOSAL MANAGEMENT</div></div><button onClick={()=>setOpen(false)} className="ml-auto lg:hidden" aria-label="Close navigation"><X/></button></div><nav className="space-y-1 px-3 py-5">{nav.map(({to,label,icon:Icon})=><NavLink key={to} to={to} onClick={()=>setOpen(false)} className={({isActive})=>`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${isActive?'bg-white/12 text-white':'text-blue-100 hover:bg-white/7 hover:text-white'}`}><Icon size={19}/>{label}</NavLink>)}</nav><div className="absolute inset-x-3 bottom-4 rounded-xl border border-white/10 bg-white/5 p-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-brand-600 font-bold">{user?.name?.[0]}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{user?.name}</div><div className="truncate text-xs text-blue-200">{user?.role?.name}</div></div><button onClick={async()=>{await logout();navigate('/login')}} aria-label="Log out" title="Log out"><LogOut size={18}/></button></div></div></aside>{open&&<button className="fixed inset-0 z-30 bg-black/30 lg:hidden" onClick={()=>setOpen(false)} aria-label="Close menu"/>}<div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center border-b border-slate-200 bg-white/95 px-4 backdrop-blur sm:px-6"><button className="mr-3 lg:hidden" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu/></button><span className="text-sm text-slate-500">RT</span><ChevronRight size={14} className="mx-2 text-slate-400"/><span className="text-sm font-semibold text-navy-900">{title}</span><div className="ml-auto flex items-center gap-2"><NavLink to="/notifications" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Notifications"><Bell size={20}/></NavLink><NavLink to="/profile" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Profile"><UserRound size={20}/></NavLink></div></header><main className="p-4 sm:p-6 lg:p-8"><Outlet/></main></div></div>}
